CONFIG_NAME: bird

dataset_name: birds
data_dir: ./data/birds

gpu_id: 0
imsize: 256
z_dim: 100
cond_dim: 256
manual_seed: 100
cuda: True

stamp: 'normal'
state_epoch: 0
max_epoch: 1301
batch_size: 64
nf: 32
ch_size: 3

model: base

gen_interval: 1
test_interval: 10
save_interval: 10

truncation: True
trunc_rate: 0.88

sample_times: 11 #10
npz_path: ./data/birds/npz/bird_val256_FIDK0.npz
example_captions: ./example_captions/bird.txt
samples_save_dir: ./samples/bird/
checkpoint: ./final_models/birds_1300e/df_itac_Lr_930.pth
save_image: False
val_save_dir: ./vals/bird/

TEXT:
    USE_CLIP: False
    WORDS_NUM: 18
    EMBEDDING_DIM: 256
    CAPTIONS_PER_IMAGE: 10
    DAMSM_NAME: ./data/birds/DAMSMencoder/text_encoder200.pth

AUG:
    TRAIN: True
    TRAIN_A: 0.2
    TRAIN_MSE_MARGIN: 0.2
    TRAIN_WARM_UP_EPOCH: 100
    CAL_P: 0.05
    EMBEDDING_DIM: 256
    DIR: ./cov/DAMSM/birds/